MySQL:
  enabled: false
  host: 'localhost'
  database: 'db'
  username: 'user'
  password: 'pass'
  port: 3306

Settings:
  save-interval: 600 # segundos
  check-interval: 300 # segundos
  command: vips
  aliases: [vip, areavip]

Messages:
  invalid-vip: '&cEsse VIP não existe!'
  invalid-duration: '&cO tempo informado é inválido!'
  offline-player: '&cEsse jogador está offline!'
  vip-expired:
    - ''
    - '&cO seu {vip} &cexpirou!'
    - ''
  join-message:
    - ''
    - '{tag} {player} &7entrou no servidor!'
    - ''

VIPs:
  Darkness:
    tag: '&8[VipDarkness]'
    use-join-message: false
    commands:
      activate:
        - 'tm bc &8{player}\n&ftornou-se &8[VipDarkness]&f!'
      remove:
        - 'pex user {player} group remove Darkness'
      add:
        - 'pex user {player} group add Darkness'
    display:
      type: SKULL_ITEM
      owner: 'eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWFjOTFhYjI1ODM2ZDEzNDgzODY0Y2RkYmQ0MzJkYmIyMmQ0YWMyOTNmMWM5OWZiMjg5MTljZjM5YzMifX19'
      name: '&8[VipDarkness]'
      lore:
        - '&7Abaixo estão as informações'
        - '&7desse VIP:'
        - ''
        - ' &8▶ &7Tempo restante: &f{remaining}'
        - ' &8▶ &7Expira em: &f{expiration_date}'
        - ''
        - '&7Clique para trocar de VIP!'

Date-Formatter:
  format: 'dd/MM/yyyy HH:mm'
  never: '-/-'

Time-Formatter:
  second: '&7segundo&f'
  seconds: '&7segundos&f'
  minute: '&7minuto&f'
  minutes: '&7minutos&f'
  hour: '&7hora&f'
  hours: '&7horas&f'
  day: '&7dia&f'
  days: '&7dias&f'
  expired: -/-